[package]
name = "luckysix"
version = "0.0.1"
edition = "2021"

[dependencies]
ethers = "2.0"
chrono = "0.4.31"
tokio = { version = "1.33.0", features = ["full"] }
config = "0.13.1"
lazy_static = "1.4.0"
serde = "1.0.190"
